apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: simple-product-api
  name: persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/