apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-product-api
  name: app-nodeport
spec:
  type: NodePort
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30003
  selector:
    name: app-pod