apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
    app: simple-product-api
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: app
        app: simple-product-api
        name: app-pod 
    spec:
      containers:
        - image: pedrohlucena/simple_product_api:latest
          name: app
          ports:
            - containerPort: 3003
          resources: {}
      restartPolicy: Always
status: {}
